include: arc_common_yaml
task: arc_easy_ny
dataset_name: ny
dataset_kwargs:
  data_files:
    validation: eval/data/ai2_arc_easy_validation_english2chichewa_microsoft_translated.jsonl
    test: eval/data/ai2_arc_easy_test_english2chichewa_microsoft_translated.jsonl
doc_to_text: "Funso: {{question}}\nYankho:"
