include: arc_common_yaml
task: arc_challenge_mri
dataset_name: mri
dataset_kwargs:
  data_files:
    validation: eval/data/ai2_arc_hard_validation_english2Maori_microsoft_translated.jsonl
    test: eval/data/ai2_arc_hard_test_english2Maori_microsoft_translated.jsonl
doc_to_text: "PÄtai: {{question}}\nWhakautu:"
