tag:
  - ai2_arc
task: arc_challenge_chat_mri
dataset_path: json
dataset_name: mri
output_type: generate_until
training_split: null
validation_split: validation
test_split: test
fewshot_split: validation
dataset_kwargs:
  data_files:
    validation: eval/data/maori/ai2_arc_hard_validation_english2Maori_microsoft_translated.jsonl
    test: eval/data/maori/ai2_arc_hard_test_english2Maori_microsoft_translated.jsonl
doc_to_text: 'I runga i te pātai e whai ake nei me ngā kōwhiringa e whā (A, B, C me D), tīpakohia te whakautu pai rawa.\nPātai: {{question.strip()}}\nA. {{choices.text[0]}}\nB. {{choices.text[1]}}\nC. {{choices.text[2]}}{% if choices.text|length > 3 %}\nD. {{choices.text[3]}}{% endif %}\nMe mutu tō whakautu ki te kī "Ko te whakautu pai ko [the_answer_letter]" ā, ko te [the_answer_letter] ko tētahi o A, B, C, D.'
gen_prefix: 'Ko te whakautu pai ko'
fewshot_delimiter: "\n\n"
doc_to_target: "{{ 'ABCD'[answerKey|int - 1] if answerKey|string in '1234' else answerKey }}"
num_fewshot: 0
generation_kwargs:
  max_gen_toks: 100
  until:
    - "\n\n"
    - "."
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
    ignore_case: true
    ignore_punctuation: true
filter_list:
  - name: remove_whitespace
    filter:
      - function: remove_whitespace
      - function: take_first
metadata:
  version: 1.0
