tag:
  - multiple_choice
task: hellaswag_ny
dataset_path: json
dataset_kwargs:
  data_files:
    validation: eval/data/chichewa/hellaswag_validation_english2chichewa_microsoft_translated.jsonl 
  trust_remote_code: true
  download_mode: force_redownload
output_type: multiple_choice
training_split: null
validation_split: validation
test_split: null
process_docs: !function utils.process_docs
doc_to_text: "{{query}}"
doc_to_target: "{{gold}}"
doc_to_choice: "{{choices}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0 