task: piqa_mri
dataset_path: json
dataset_kwargs:
  data_files:
    train: eval/data/piqa_train_english2Maori_microsoft_translated.jsonl
    validation: eval/data/piqa_validation_english2Maori_microsoft_translated.jsonl
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: null
doc_to_text: "PƒÅtai: {{goal}}\nWhakautu:"
doc_to_target: label
doc_to_choice: "{{[sol1, sol2]}}"
should_decontaminate: true
doc_to_decontamination_query: goal
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
