include: xstorycloze_common_yaml
task: xstorycloze_mri
dataset_name: mri
dataset_kwargs:
  data_files:
    train: eval/data/maori/xstory_cloze_train_english2Maori_microsoft_translated.jsonl
    eval:  eval/data/maori/xstory_cloze_eval_english2Maori_microsoft_translated.jsonl